services:
  dokuwiki:
    image: docker.io/bitnami/dokuwiki:20240206
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /mnt/e/dokuwiki:/bitnami/dokuwiki
    environment:
      - DOKUWIKI_PASSWORD=doku08
volumes:
  dokuwiki_data:
    driver: local
