github.com:
    users:
        shingoo0812:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: shingoo0812
