services:
  nvim:
    build:
      context: ..
      dockerfile: Dockerfile/Dockerfile
    image: dotfiles-nvim
    container_name: dotfiles-nvim
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    environment:
      - TERM=wezterm
      - JUPYTER_RUNTIME_DIR=/tmp/jupyter/runtime
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /mnt:/mnt                 # All Windows drives (C, F, etc.) dynamically
      - ~/workspace:/workspace
      - /home/shingo:/wsl/home
      - nvim_data:/root/.local/share/nvim    # Host workspace (read-write)

volumes:
  nvim_data:
