services:
  nvim:
    build:
      context: ..
      dockerfile: Dockerfile/Dockerfile
    image: dotfiles-nvim
    container_name: dotfiles-nvim
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /mnt:/mnt                 # All Windows drives (C, F, etc.) dynamically
      - ~/workspace:/workspace    # Host workspace (read-write)
